### ISSUE TITLE
Speed formatting in coding history is always IPS

### ISSUE THREAD

**Issue by hocksteindw** [brnco/avmpi_scripts#10]
Hi!

It looks like IPS is the hard-coded value in the Airtable formatting for the CodingHistory assemblage. When you have a moment, if you could modify it to grab from "Speed Type" that would rock! I'd do this meself but it seems like there are a lot of functions cascading into each other, and I don't wanna break 'em

**Comment by brnco** [comment]
Should be fixed now

**Comment by hocksteindw** [comment]
Thx!
