### ISSUE TITLE
A few fixes to embed_md.py

### ISSUE THREAD

**Issue by hocksteindw** [brnco/avmpi_scripts#5]
This is a huge, HUGE timesaver, thank you! Just a few formatting things to note and feature requests:

 - [x] Pulling OriginationDate/OriginationTime from either the A-D Transfer record or Digital Asset Creation Date/Time (ISO formatted) would be wonderful as the Steinberg stuff currently doesn't embed it. I think new versions might, but still, I feel OK about pulling from these fields and overwriting the data.

- [x] The CodingHistory field is almost there, but looks a little wonky. Here's what it looks like now:

```
A=ANALOGUE,M=Stereo,T=Cassette-122MkIII-20117; 120117; 1.875.
A=PCM,F=96000,W=24,T=ADC-Aurora(n)-92149; 6023092149
```
Ideally, this would be formatted:

```
A=ANALOGUE,M=Stereo,T=Tascam 122 MkIII; SN120117; 1.875 IPS
A=PCM,F=96000,W=24,T=Lynx Aurora (n); SN6023092149
```
I see that you're formatting this in Airtable, which yes, is way cleaner. If there are complications that make spitting out some of this info a little too crazy or it feels like makework, that's totally fine, the formatting we have now is enough to trace stuff back if an issue arises; it's just not quite as  legible to someone else looking at the file.

Keep in mind that this functionality would ideally account for something like a DAT transfer, which does not read ANALOGUE on the first line - not sure if that's hard-coded in, but if you need to add a Dig/Analogue field that articulates this for the code, that's totally fine. I can handle the more complex/insane deliverables, like the multitrack or IRENE files we're getting back, but it'd be great if open-reel, cassette, and DAT all format according to that EBU/FADGI rec.

One thing I just realized we're missing is a field for the reference fluxivity of the analog transfer; this would ideally go in the first line after speed...maybe we'll save that for later :)

- [x] I think my name actually goes into ITCH, not IENG. IENG is for the engineer originally responsible for recording. That was probably my bad in the key I gave you, I get them mixed up sometimes.

- [x] Finally, I just want to ensure that one of the exceptions included in the script is something like

```
Error: Filename lookup failed for [filename]. Matching record in Airtable does not exist.
```

If there's a logical place to park that or that granularity is available. This might give me some clues as to some meatdata file naming if it happens. I have a feeling I might be chasing my own tail on that kinda thing once in a while.

Thank you so much!!!!!!!

**Comment by brnco** [comment]
Dan, these should all be addressed in [b5b9a37](https://github.com/brnco/avmpi_scripts/commit/b5b9a37f8932d8e795e009ba9637cad0763e2b35).

Give it a shot and let me know

**Comment by hocksteindw** [comment]
Looks great, thanks sooooo much! Two more small things: 
I don't think the first line of the CodingHistory should have a period at the end
ICOP can map from Physical Assets -> "Item Rights," right now that field is mostly blank but I think it may eventually recieve a default value. Wasn't sure if I had included that.

That's it for now! Yay!

**Comment by brnco** [comment]
Dan, implemented those suggestions as well. You can see the ICOP mapping in `field_mappings.json`.

One thing I forgot to note is that the OriginationDate and OriginationTime are handled by BWFMetaEdit directly, using the `TIMESTAMP` option, so we're inheriting whatever formatting from that.

**Comment by hocksteindw** [comment]
Great! Thanks! Was not aware of the `TIMESTAMP` feature. Will pull, should be all set beyond that until we do a stage 2. Thanks again **so much**, you have no idea how much time this all saves me.
